num_agents_per_generation: 1
num_episodes_per_agent: 200
num_generations: 20
copier_config:
  activation: relu
  obs_dim: 500
  l2_alpha: 0.01
  width: 16
  epochs: 150
  batch_size: 32
dqn_config:
  gamma: 0.998
  epsilon: 0.99
  lr: 0.001
  mem_size: 5000
  batch_size: 64
  epsilon_dec: 0.97
  epsilon_end: 0.001
dqn_misc:
  episodes_until_learn: 15
